config/routes.rb
Rails.application.routes.draw do
	root 'home#index'
  	resources :users, only: [:new, :create]
 	resources :sessions, only: [:new, :create, :destroy, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	resources :profiles

  	resources :search, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  scope :last_published, -> {order("created_at DESC")}
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :profiles

  validates_presence_of :name, :username, :email, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :current_user, :user_signed_in?

	private
	def current_user
		@current_user = User.find_by(id: session[:user_id])
	end

	def user_signed_in?
		current_user
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_profile, only: [:show, :edit, :update, :destroy]
	def index
		is_remote = params[:is_remote]

		if is_remote
			@profiles = Profile.last_published.where({is_remote: is_remote})
		else
			@profiles = Profile.last_published
		end
	end
	def show
		@profile = Profile.find(params[:id])
	end

	def edit
		@profile = Profile.find(params[:id])
	end

	def update
		@profile = Profile.find(params[:id])
		if @profile.update(profile_params)
			redirect_to @profile
		end
	end

	def new
		@profile = Profile.new
	end

	def create
		@profile = Profile.new(profile_params)
		@profile.user = current_user
		if @profile.save
			redirect_to @profile
		else
			redirect_to root_path
		end
	end

	def destroy
		@profile = Profile.find(params[:id])
		@profile.destroy

		redirect_to profiles_path
	end

	private
	def profile_params
		params.require(:profile).permit(:alias, :description, :is_remote, :price, :user)
	end

	def set_profile
		@profiles = Profile.find(params[:id])
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def index
		keyword = "%#{params[:q]}"

		@profiles = Profile.where(["alias LIKE ? or description LIKE ? ", keyword, keyword])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  	def new	
  	end

  	def show
  	end

  	def create
  		user = User.find_by(email: params[:email])
  		if user && user.authenticate(params[:password])
  			session[:user_id] = user.id
  			redirect_to root_path, notice: "Login succesful"
  		else
  			flash.now.alert = "email or pàssword incorrect"
  			render :new
  		end
  	end

  	def destroy
  		session.delete(:user_id)
  		redirect_to root_path, notice: "Session closed !"
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		redirect_to new_user_path
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to root_path, notice: "Account created correctly!"
		else
			render :new
		end
	end

	private
		def user_params
			params.require(:user).permit(:name, :last_name, :username, :country, :date_of_birth, :email, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Udemy1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/partials/navigation' %>
    <section style="margin-top: 25px;">
      <div class="container">
        <%= yield %>  
      </div>
    </section>
  </body>
</html>

app/views/layouts/partials/_msg.html.erb
<% flash.each do |key, value| %>
<%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

app/views/layouts/partials/_navigation.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    <% end -%>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      
  	<%= link_to "Home", root_path, class: "navbar-item" %>
  	<% if user_signed_in? %>
	  	<%= link_to "Profile", profiles_path, class: "navbar-item" %>
			<%= link_to "Publish Profile", new_profile_path, class: "navbar-item" %>
		<% end -%>
		<%= link_to "Search", search_index_path, class: "navbar-item" %>

      <!-- <a class="navbar-item">
        Documentation
      </a> -->

      <!-- <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div> -->
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
        	<% if user_signed_in? %>
        		<%= link_to current_user.email, session_path(current_user), class: "button is-primary" %>
        		<%= link_to "Log out", session_path(current_user), method: :delete, class: "button is-light" %>
        	<% else %>
	        	<%= link_to "Sign up", new_user_path, class: "button is-primary" %>
	          <%= link_to "Log in", new_session_path, class: "button is-light" %>
        	<% end %>
          
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/profiles/_form.html.erb
<%= form_with(model: @profile) do |f| %>
	<div class="field">
		<%= f.label :alias %>
		<%= f.text_field :alias, class: "input" %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description, class: "textarea" %>
	</div>
	<div class="field">
		<%= f.label :price %>
		<%= f.number_field :price, class: "input" %>
	</div>
	<div class="field">
		<%= f.label :is_remote %>
		<%= f.check_box :is_remote, class: "checkbox" %>
	</div>
	<div class="field">
		<%= f.label :user_id %>
		<%= f.text_field :user_id, class: "input" %>
	</div>
	<div class="field">
		<%= f.submit nil, class: "button is-primary is-fullwidth" %>
	</div>
<% end -%>

app/views/profiles/_profiles.html.erb
<% @profiles.each do |profile| %>
		<!-- <li><%= link_to profile.alias.capitalize, profile %></li> -->
	

	<article class="media">
	  <figure class="media-left">
	    <p class="image is-64x64">
	      <img src="https://bulma.io/images/placeholders/128x128.png">
	    </p>
	  </figure>
	  <div class="media-content">
	    <div class="content">
	      <p>
	        <strong><%= link_to profile.alias.capitalize, profile %></strong>
	        <br>
	        <%= profile.description %>
	      </p>
	    </div>
	    <!-- <nav class="level is-mobile">
	      <div class="level-left">
	        <a class="level-item">
	          <span class="icon is-small"><i class="fas fa-reply"></i></span>
	        </a>
	        <a class="level-item">
	          <span class="icon is-small"><i class="fas fa-retweet"></i></span>
	        </a>
	        <a class="level-item">
	          <span class="icon is-small"><i class="fas fa-heart"></i></span>
	        </a>
	      </div>
	    </nav> -->
	  </div>
	  <!-- <div class="media-right">
	    <button class="delete"></button>
	  </div> -->
	</article>

<% end -%>

app/views/profiles/edit.html.erb
<h3 class="columns">Edit Profile</h3>
<%= render 'profiles/form', profile: @profile %>

app/views/profiles/index.html.erb
<%= link_to "Remotes", profiles_path(is_remote: true), class: "tag" %>
<%= link_to "In site", profiles_path(is_remote: false), class: "tag" %>
<%= link_to "Clear filter", profiles_path, class: "tag" %>
<hr/>
<%= render 'profiles/profiles' %>

app/views/profiles/new.html.erb
<h3 class="columns">Publish Profile</h3>
<%= render 'profiles/form', profile: @profile %>

app/views/profiles/show.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= @profile.alias %>
      </h1>
      <h2 class="subtitle">
      	 <strong>Description:</strong> <%= @profile.description %>
      </h2>
      <h2 class="subtitle">
		<strong>Price:</strong> <%= @profile.price %>
      </h2>
    </div>
  </div>
</section>
	<%= link_to "Edit", edit_profile_path %> - <%= link_to "Destroy", profile_path, method: :delete, data: {confirm: "Are you sure you want to delete profile?"} %>

app/views/search/index.html.erb
<%= form_tag search_index_path, method: :get do %>
	<div class="field has-addons">
	  <div class="control">
	    <%= text_field_tag :q, params[:q], class: "input", placeholder: "Keyword by alias or description", style: "width: 800px;" %>
	  </div>
	  <div class="control">
	    <%= submit_tag "Search", class: "button is-primary" %>
	  </div>
	</div>
<% end -%>

<br>
<%= render 'profiles/profiles' %>

app/views/users/new.html.erb
<h2>Create Account</h2>
<%= form_with(model: @user, local: true) do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name, autofocus: true %>
	</div>
	<div>
		<%= f.label :last_name %>
		<%= f.text_field :last_name, autofocus: true %>
	</div>
	<div>
		<%= f.label :username %>
		<%= f.text_field :username, autofocus: true %>
	</div>
	<div>
		<%= f.label :country %>
		<%= f.text_field :country, autofocus: true %>
	</div>
	<div>
		<%= f.label :date_of_birth %>
		<%= f.text_field :date_of_birth, autofocus: true %>
	</div>
	<div>
		<%= f.label :email %>
		<%= f.email_field :email, autofocus: true %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.password_field :password, autofocus: true %>
	</div>
	<div>
		<%= f.submit "Register" %>
	</div>
<% end -%>